apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sprayproxy-qncu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sprayproxy-qncu
    app.kubernetes.io/part-of: sprayproxy-1
  name: sprayproxy-qncu
spec:
  rules:
  - host: sprayproxy-qncu-pkumari-tenant.192.168.49.2.nip.io
    http:
      paths:
      - backend:
          service:
            name: sprayproxy-qncu
            port:
              number: 9443
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
