apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sprayproxy-qncu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sprayproxy-qncu
    app.kubernetes.io/part-of: sprayproxy-1
  name: sprayproxy-qncu
  namespace: pkumari-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: sprayproxy-qncu
      app.kubernetes.io/name: sprayproxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sprayproxy-qncu
        app.kubernetes.io/name: sprayproxy
    spec:
      containers:
      - args:
        - server
        env:
        - name: SPRAYPROXY_SERVER_BACKEND
        - name: SPRAYPROXY_SERVER_ENABLE_DYNAMIC_BACKENDS
          value: "true"
        image: quay.io/redhat-user-workloads-stage/pkumari-tenant/sprayproxy-1/sprayproxy-qncu@sha256:2bf559c91327e8689317368c595fd1ecdb1cf2ebd22105d757aa23e9c141def3
        name: sprayproxy
        ports:
        - containerPort: 8080
          name: server
        - containerPort: 9443
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
      - args:
        - --secure-listen-address=0.0.0.0:9443
        - --upstream=http://127.0.0.1:8080/
        - --ignore-paths=/proxy,/healthz
        - --logtostderr=true
        - --v=10
        - --tls-cert-file=/etc/tls/tls.crt
        - --tls-private-key-file=/etc/tls/tls.key
        image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.12
        name: kube-rbac-proxy
        ports:
        - containerPort: 9443
          name: proxy-https
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/tls
          name: tls
          readOnly: true
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:6000/
        - --logtostderr=true
        - --v=10
        image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.12
        name: kube-rbac-metrics
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
      serviceAccountName: sprayproxy
      volumes:
      - name: tls
        secret:
          defaultMode: 420
          secretName: sprayproxy-tls
status: {}
