apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: sprayproxy-tls
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sprayproxy-qncu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sprayproxy-qncu
    app.kubernetes.io/part-of: sprayproxy-1
  name: sprayproxy-qncu
  namespace: pkumari-tenant
spec:
  ports:
  - name: proxy-https
    port: 9443
    protocol: TCP
    targetPort: 0
  selector:
    app.kubernetes.io/instance: sprayproxy-qncu
    app.kubernetes.io/name: sprayproxy
status:
  loadBalancer: {}
